@startuml
autonumber
skinparam sequenceArrowThickness 2

Client -> RestaurantPageController: showHomePage()
Client <-- RestaurantPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: showAdminPanel()
Client <-- AdminPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: uploadMenu()
Client -> FileService: saveMenuInProjectDir()
Client <-- FileService: return

Client <-- AdminPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: createdReservationFromAdmin()
Client -> ReservationServiceImpl: createReservation()
Client -> EmailService: sendHTMLEmail()
Client <-- EmailService: return

Client <-- ReservationServiceImpl: return

Client <-- AdminPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: cancelReservationFromAdmin()
Client -> ReservationServiceImpl: cancelReservation()
Client -> EmailService: sendHTMLEmail()
Client <-- EmailService: return

Client <-- ReservationServiceImpl: return

Client <-- AdminPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: getReservationsConfirmedByDate()
Client -> ReservationServiceImpl: getAllReservationByDay()
Client <-- ReservationServiceImpl: return

Client <-- AdminPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: getReservationsToday()
Client -> ReservationServiceImpl: getReservationsForTableToday()
Client <-- ReservationServiceImpl: return

Client <-- AdminPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: showAdminPanel()
Client <-- AdminPageController: return

Client -> RestaurantPageController: showHomePage()
Client <-- RestaurantPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: showAdminPanel()
Client <-- AdminPageController: return

Client -> AdminPageController: getReservationFormDto()
Client <-- AdminPageController: return

Client -> AdminPageController: uploadMenu()
Client -> FileService: saveMenuInProjectDir()
Client <-- FileService: return

Client <-- AdminPageController: return

Client -> RestaurantPageController: showHomePage()
Client <-- RestaurantPageController: return

Client -> RestaurantPageController: showHomePage()
Client <-- RestaurantPageController: return

Client -> RestaurantPageController: showReservationPage()
Client <-- RestaurantPageController: return

Client -> RestaurantPageController: createReservation()
Client -> ReservationServiceImpl: createReservation()
Client -> EmailService: sendHTMLEmail()
Client <-- EmailService: return

Client <-- ReservationServiceImpl: return

Client <-- RestaurantPageController: return

Client -> RestaurantPageController: showHomePage()
Client <-- RestaurantPageController: return

Client -> RestaurantPageController: showCancelPage()
Client <-- RestaurantPageController: return

Client -> RestaurantPageController: cancelReservation()
Client -> ReservationServiceImpl: cancelReservation()
Client -> EmailService: sendHTMLEmail()
Client <-- EmailService: return

Client <-- ReservationServiceImpl: return

Client <-- RestaurantPageController: return

Client -> RestaurantPageController: showHomePage()
Client <-- RestaurantPageController: return

Client -> RestaurantPageController: downloadMenu()
Client -> FileService: getMenu()
Client <-- FileService: return

Client <-- RestaurantPageController: return

@enduml
