= Введение к RestaurantApp
Техническая документация учебного приложения RestaurantApp
:doctype: book
:toc:
:toclevels: 1

RestaurantApp — это учебное приложение, написанное на **Java 17** с использованием **Spring Boot**, **Maven**, **PostgreSQL**, **Liquibase**, **In‑Memory Security** и **Thymeleaf**. Приложение позволяет резервировать столики в ресторане, отслеживать пересечение интервалов бронирования и выполнять отмену резерваций.

== Структура документации

* xref:02-architecture.adoc[Архитектура приложения]
* xref:03-installation.adoc[Установка]
* xref:04-configuration.adoc[Конфигурация]
* xref:05-db.adoc[Схема и описание базы данных]
* xref:06-security.adoc[Безопасность]
* xref:07-usage.adoc[Использование]
* xref:08-appendix.adoc[Приложения]

=== Цель проекта

* Демонстрация принципов построения RESTful-приложения на Java 17 и Spring Boot.
* Практика работы с реляционной базой данных PostgreSQL и управления схемой с помощью Liquibase.
* Настройка простой безопасности с использованием In-Memory Authentication (Spring Security).
* Шаблонизация серверного рендеринга с помощью Thymeleaf.

=== Основные возможности

* Просмотр списка доступных столиков на текущий день и их вместимости с панели администратора.
* Создание новой резервации: указание даты и времени, количества гостей, ввод контактных данных.
* Приложение само находит столик подходящей вместимости для заданного количества гостей.
* Если на заданный промежуток времени и заданное количество гостей не существует свободного столика, приложение дает ответ о том, что резервация на это время невозможна.
* Если количество гостей меньше или равно вместимости хотя бы одного свободного в это время столика, резервация создается на этот тот столик, у которого вместимость ближе всего к заданному количеству гостей
* Отображение статуса резервации (CONFIRMED, CANCELLED).
* Пользователь получает email с подтверждением резервации и кодом резервации, который можно применить для отмены резервации
* В базе данных создается флаг is_admin = true в случае, если резеравция была создана с панели администратора.
* Возможна отмена резервации и управление ролями пользователя (администратор может просматривать и создавать резервации от имени клиентов).
* Администратор может закачать pdf файл меню с панели администратора
* Пользователь может скачать файл меню с общедоступной страницы

=== Технологический стек

- **Язык:** Java 17
- **Фреймворк:** Spring Boot (Web, Data JPA, Security, Mail)
- **СУБД:** PostgreSQL
- **Миграции:** Liquibase
- **Шаблонизатор:** Thymeleaf
- **Сборка:** Maven
- **Безопасность:** In-memory Authentication


